# Generated by Django 3.2.6 on 2021-08-27 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('objeto', models.TextField()),
                ('contratista', models.CharField(max_length=150)),
                ('numero_contrato', models.IntegerField(verbose_name='Número Contrato')),
                ('estado', models.CharField(choices=[('EJ', 'En ejecución'), ('F', 'Finalizado'), ('S', 'Suspendido'), ('C', 'Cancelado')], max_length=2)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('terminal', models.CharField(choices=[('BUN', 'Buenaventura'), ('CTG', 'Cartagena'), ('BOG', 'Bogotá')], max_length=3)),
                ('valor_proyecto', models.IntegerField(blank=True, null=True)),
                ('programado', models.FloatField(blank=True, max_length=5, null=True)),
                ('avance', models.FloatField(blank=True, max_length=5, null=True)),
                ('responsable', models.CharField(blank=True, max_length=50)),
                ('interventoria', models.BooleanField(default=False)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('valor_pago', models.IntegerField(blank=True, null=True)),
                ('concepto_pago', models.CharField(max_length=150)),
                ('numero_factura', models.CharField(blank=True, max_length=15)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='imagenes/%Y/%m/%d/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('documento', models.FileField(upload_to='documentos/%Y/%m/%d/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Cambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150)),
                ('afecta_tiempo', models.BooleanField(default=False, verbose_name='Afecta en Tiempo')),
                ('duracion', models.IntegerField(blank=True, null=True)),
                ('afecta_costo', models.BooleanField(default=False, verbose_name='Afecta en Costo')),
                ('costo', models.IntegerField(blank=True, null=True)),
                ('fecha_de_cambio', models.DateField()),
                ('genero_documento', models.BooleanField(default=False)),
                ('nombre_documento', models.CharField(max_length=150)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('programado', models.FloatField(blank=True, max_length=5, null=True)),
                ('avance', models.FloatField(blank=True, max_length=5, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.proyecto')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
