# Generated by Django 3.2.6 on 2021-09-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_auto_20210827_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='valor_proyecto',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
