# Generated by Django 3.2.6 on 2021-09-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0003_alter_proyecto_valor_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='terminal',
            field=models.CharField(choices=[('BUN', 'Buenaventura'), ('CTG', 'Cartagena'), ('BOG', 'Bogotá'), ('GLB', 'Global')], max_length=3),
        ),
    ]
