# Generated by Django 3.2.6 on 2021-10-06 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0004_alter_proyecto_terminal'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibliotecaProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cotizaciones', models.IntegerField(blank=True, null=True)),
                ('area', models.CharField(max_length=100, verbose_name='Área')),
                ('impacto', models.TextField()),
                ('presupuesto', models.IntegerField(blank=True, null=True)),
                ('documento', models.FileField(upload_to='bibliotecap/%Y/%m/%d/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'ordering': ['creado'],
            },
        ),
    ]
