# Generated by Django 3.2.6 on 2021-10-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0005_bibliotecaproyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliotecaproyecto',
            name='documento',
            field=models.FileField(blank=True, upload_to='bibliotecap/%Y/%m/%d/'),
        ),
    ]
