# Generated by Django 3.2.6 on 2021-10-20 15:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0007_auto_20211020_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectomacro',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='proyectomacro',
            name='avance',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='proyectomacro',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyectomacro',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyectomacro',
            name='fecha_inicio',
            field=models.DateField(default=datetime.datetime(2021, 10, 20, 15, 15, 18, 501186, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyectomacro',
            name='programado',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='proyectomacro',
            name='terminal',
            field=models.CharField(choices=[('BUN', 'Buenaventura'), ('CTG', 'Cartagena'), ('BOG', 'Bogotá'), ('GLB', 'Global')], default='CTG', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyectomacro',
            name='uc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Usuario que Crea'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyectomacro',
            name='um',
            field=models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica'),
        ),
        migrations.AddField(
            model_name='proyectomacro',
            name='valor_proyecto',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
