# Generated by Django 3.2.6 on 2021-11-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0008_auto_20211020_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectomacro',
            name='estado',
            field=models.CharField(choices=[('EJ', 'En ejecución'), ('F', 'Finalizado'), ('S', 'Suspendido'), ('C', 'Cancelado')], default='EJ', max_length=2),
            preserve_default=False,
        ),
    ]
