# Generated by Django 3.2.6 on 2021-11-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0009_proyectomacro_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyectomacro',
            options={'ordering': ['-creado']},
        ),
    ]
