# Generated by Django 3.2.6 on 2022-01-28 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos', '0012_documentomacro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='um',
            field=models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica'),
        ),
        migrations.AlterField(
            model_name='actividadmacro',
            name='um',
            field=models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica'),
        ),
        migrations.AlterField(
            model_name='bibliotecaproyecto',
            name='um',
            field=models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica'),
        ),
        migrations.AlterField(
            model_name='cambio',
            name='um',
            field=models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica'),
        ),
        migrations.AlterField(
            model_name='documentomacro',
            name='um',
            field=models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='um',
            field=models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica'),
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True, verbose_name='Usuario que modifica')),
                ('comentarios', models.TextField()),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='proyectos.proyecto')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Crea')),
            ],
            options={
                'ordering': ('creado',),
            },
        ),
    ]
