# Generated by Django 3.2.6 on 2022-01-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0014_comentarios_activo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ('-creado',)},
        ),
    ]
