# Generated by Django 3.2.6 on 2022-04-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0015_alter_comentarios_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='numero_contrato',
            field=models.CharField(max_length=150, verbose_name='Número Contrato'),
        ),
    ]
