# Generated by Django 3.2.6 on 2022-04-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0016_alter_proyecto_numero_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='valor_proyecto',
            field=models.IntegerField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
