# Generated by Django 3.2.6 on 2022-04-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0020_alter_proyectomacro_valor_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='valor_proyecto_planeado',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Costo Planeado'),
        ),
        migrations.AddField(
            model_name='proyectomacro',
            name='valor_proyecto_planeado',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Costo Planeado'),
        ),
    ]
